// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cldyihpqmlwequmnrdsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZHlpaHBxbWx3ZXF1bW5yZHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTk1ODgsImV4cCI6MjA2OTEzNTU4OH0.Zy7tdCvG9ui751jCvxMIJXTHEI-3nhY6WDs-ynG0GE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});